### ISSUE TITLE
Возможность включить старый ПКМ

### ISSUE THREAD

**Issue by IvanDonFon** [WalkmanNik/Osiris-SS13-Hi-RP#18]
### Проблема

Новый ПКМ лично для меня - тот ещё Shit. Да, и уверен - не только для меня. + там нету некоторых нужных функций

### Решение

В Preferences можно будет включить старый ПКМ

**Comment by FreimK** [comment]
Поддерживаю. Старый ПКМ привычней, да и куча штук именно под него заточена. Новый, конечно, красивый, но возможность переключаться между ними не помешает.

**Comment by WalkmanNik** [comment]
На данный момент я не представляю это возможным, т.к. для нового меню необходима фиксация ПКМ в клиенте. Я уже обсуждал этот вопрос со многими другими игроками и все согласились с нынешним назначением ПКМ. Просто потихоньку сидим и допиливаем функционал.

**Comment by IvanDonFon** [comment]
> На данный момент я не представляю это возможным, т.к. для нового меню необходима фиксация ПКМ в клиенте. Я уже обсуждал этот вопрос со многими другими игроками и все согласились с нынешним назначением ПКМ. Просто потихоньку сидим и допиливаем функционал.
